\(repo : Text) ->
\(arch : Text) ->
  [ "https://ger.mirror.pkgbuild.com/${repo}/os/${arch}"
  , "https://ftp.halifax.rwth-aachen.de/archlinux/${repo}/os/${arch}"
  , "https://mirror.wtnet.de/arch/${repo}/os/${arch}"
  , "https://archlinux.mailtunnel.eu/${repo}/os/${arch}"
  , "https://mirror.chaoticum.net/arch/${repo}/os/${arch}"
  , "https://archlinux.uk.mirror.allworldit.com/archlinux/${repo}/os/${arch}"
  , "https://ftp.sh.cvut.cz/arch/${repo}/os/${arch}"
  , "http://mirror.pseudoform.org/${repo}/os/${arch}"
  , "http://ftp.halifax.rwth-aachen.de/archlinux/${repo}/os/${arch}"
  , "http://mirror.chaoticum.net/arch/${repo}/os/${arch}"
  , "https://mirrors.uni-plovdiv.net/archlinux/${repo}/os/${arch}"
  , "https://mirror.f4st.host/archlinux/${repo}/os/${arch}"
  , "http://mirror.f4st.host/archlinux/${repo}/os/${arch}"
  , "http://archlinux.uk.mirror.allworldit.com/archlinux/${repo}/os/${arch}"
  , "https://mirror.pseudoform.org/${repo}/os/${arch}"
  , "https://archlinux.beccacervello.it/archlinux/${repo}/os/${arch}"
  , "http://ftp.sh.cvut.cz/arch/${repo}/os/${arch}"
  , "http://mirror.wtnet.de/arch/${repo}/os/${arch}"
  , "https://mirrors.atviras.lt/archlinux/${repo}/os/${arch}"
  , "http://mirrors.atviras.lt/archlinux/${repo}/os/${arch}"
  ]
