cabal-version: 3.14
name: dhalpm
version: 0.1.0.0
description:
  Please see the README on Github at <https://github.com/mmhat/dhalpm#readme>

homepage: https://github.com/mmhat/dhalpm#readme
bug-reports: https://github.com/mmhat/dhalpm/issues
author: Dominik Peteler
maintainer: haskell@with-h.at
copyright: 2022 Dominik Peteler
license: BSD-3-Clause
license-file: LICENSE
build-type: Simple
-- cabal-gild: discover test/ --include=test/*.dhall --include=test/data/**/*
extra-source-files:
  test/data/database/local/ALPM_DB_VERSION
  test/data/database/local/depends-package-1-1/desc
  test/data/database/local/depends-package-1-1/files
  test/data/database/local/depends-package-1-1/mtree
  test/data/database/local/test-package-1-1/desc
  test/data/database/local/test-package-1-1/files
  test/data/database/local/test-package-1-1/mtree
  test/data/makepkg.conf
  test/data/mirrorlist.dhall
  test/data/packages/depends-package/PKGBUILD
  test/data/packages/depends-package/depends-package-1-1-any.pkg.tar.zst
  test/data/packages/depmissing-package/PKGBUILD
  test/data/packages/depmissing-package/depmissing-package-1-1-any.pkg.tar.zst
  test/data/packages/providers-1/PKGBUILD
  test/data/packages/providers-1/providers-1-1-1-any.pkg.tar.zst
  test/data/packages/providers-2/PKGBUILD
  test/data/packages/providers-2/providers-2-1-1-any.pkg.tar.zst
  test/data/packages/test-package/PKGBUILD
  test/data/packages/test-package/test-package-1-1-any.pkg.tar.zst
  test/data/root/depends-file1
  test/data/root/depends-file2
  test/data/root/file1
  test/data/root/file2
  test/data/syncdbs/testdb/depends-package-1-1-any.pkg.tar.zst
  test/data/syncdbs/testdb/depmissing-package-1-1-any.pkg.tar.zst
  test/data/syncdbs/testdb/providers-1-1-1-any.pkg.tar.zst
  test/data/syncdbs/testdb/providers-2-1-1-any.pkg.tar.zst
  test/data/syncdbs/testdb/test-package-1-1-any.pkg.tar.zst
  test/data/syncdbs/testdb/testdb.db
  test/data/syncdbs/testdb/testdb.db.tar.gz
  test/data/syncdbs/testdb/testdb.files
  test/data/syncdbs/testdb/testdb.files.tar.gz
  test/empty.dhall
  test/install-from-build.dhall
  test/install-from-file.dhall
  test/install-from-syncdb.dhall
  test/install-with-dependency.dhall
  test/providers.dhall
  test/realworld-simple.dhall
  test/remove-orphaned.dhall

extra-files:
  ChangeLog.md
  LICENSE
  README.md

common language
  default-extensions:
    LambdaCase
    NoImplicitPrelude
    OverloadedStrings
    StrictData

  ghc-options:
    -Wall
    -Wcompat
    -Widentities
    -Wincomplete-record-updates
    -Wincomplete-uni-patterns
    -Wpartial-fields
    -Wredundant-constraints

  default-language: GHC2021

common rts
  ghc-options:
    -threaded
    -rtsopts
    -with-rtsopts=-N

library
  import: language
  hs-source-dirs: src
  build-depends:
    alpm,
    attoparsec,
    base >=4.11 && <5,
    data-default-class,
    data-fix,
    dhall,
    effectful,
    either,
    exceptions,
    ini >=0.4.0,
    log-base,
    log-effectful,
    path >=0.8.0,
    path-effectful,
    path-effectful:extra,
    prettyprinter,
    recursion-schemes,
    relude,
    text-display >=1,
    text-short,
    typed-process-effectful,
    unliftio,
    unordered-containers,
    vector,

  -- cabal-gild: discover src/ --include=src/**/*.hs --exclude=src/Import.hs
  exposed-modules:
    Run
    Types
    Types.Dhall

  other-modules:
    Import

executable dhalpm
  import: language
  import: rts
  hs-source-dirs: app/dhalpm
  main-is: Main.hs
  build-depends:
    base,
    dhalpm,
    effectful,
    log-base,
    log-effectful,
    optparse-simple,
    typed-process-effectful,

  -- cabal-gild: discover app/dhalpm/ --include=app/dhalpm/**/*.hs --exclude=app/dhalpm/Main.hs
  other-modules: Options
  other-modules: PackageInfo_dhalpm
  autogen-modules: PackageInfo_dhalpm

test-suite test
  import: language
  import: rts
  type: exitcode-stdio-1.0
  hs-source-dirs: test
  main-is: Spec.hs
  build-depends:
    QuickCheck,
    base,
    dhall,
    dhalpm,
    directory,
    effectful,
    filepath,
    hspec,
    log-base,
    log-effectful,
    path,
    path-io,
    relude,
    typed-process-effectful,

  build-tool-depends: hspec-discover:hspec-discover
  -- cabal-gild: discover test/ --include=test/**/*.hs --exclude=test/Spec.hs
  other-modules:
    RunSpec

  other-modules: PackageInfo_dhalpm
  autogen-modules: PackageInfo_dhalpm

source-repository head
  type: git
  location: https://github.com/mmhat/dhalpm
