cabal-version: 3.14
name: alpm
version: 0.1.0.0
description:
  Please see the README on Github at <https://github.com/mmhat/dhalpm#readme>

homepage: https://github.com/mmhat/dhalpm#readme
bug-reports: https://github.com/mmhat/dhalpm/issues
author: Dominik Peteler
maintainer: haskell@with-h.at
copyright: 2022 Dominik Peteler
license: BSD-3-Clause
license-file: LICENSE
build-type: Simple
-- cabal-gild: discover test/data/ --include=test/data/**/*
extra-source-files:
  test/data/database/local/ALPM_DB_VERSION
  test/data/database/local/depends-package-1-1/desc
  test/data/database/local/depends-package-1-1/files
  test/data/database/local/depends-package-1-1/mtree
  test/data/database/local/test-package-1-1/desc
  test/data/database/local/test-package-1-1/files
  test/data/database/local/test-package-1-1/mtree
  test/data/makepkg.conf
  test/data/mirrorlist.dhall
  test/data/packages/depends-package/PKGBUILD
  test/data/packages/depends-package/depends-package-1-1-any.pkg.tar.zst
  test/data/packages/depmissing-package/PKGBUILD
  test/data/packages/depmissing-package/depmissing-package-1-1-any.pkg.tar.zst
  test/data/packages/providers-1/PKGBUILD
  test/data/packages/providers-1/providers-1-1-1-any.pkg.tar.zst
  test/data/packages/providers-2/PKGBUILD
  test/data/packages/providers-2/providers-2-1-1-any.pkg.tar.zst
  test/data/packages/test-package/PKGBUILD
  test/data/packages/test-package/test-package-1-1-any.pkg.tar.zst
  test/data/root/depends-file1
  test/data/root/depends-file2
  test/data/root/file1
  test/data/root/file2
  test/data/syncdbs/testdb/depends-package-1-1-any.pkg.tar.zst
  test/data/syncdbs/testdb/depmissing-package-1-1-any.pkg.tar.zst
  test/data/syncdbs/testdb/providers-1-1-1-any.pkg.tar.zst
  test/data/syncdbs/testdb/providers-2-1-1-any.pkg.tar.zst
  test/data/syncdbs/testdb/test-package-1-1-any.pkg.tar.zst
  test/data/syncdbs/testdb/testdb.db
  test/data/syncdbs/testdb/testdb.db.tar.gz
  test/data/syncdbs/testdb/testdb.files
  test/data/syncdbs/testdb/testdb.files.tar.gz

extra-doc-files:
  CHANGELOG.md

extra-files:
  LICENSE

common language
  default-extensions:
    LambdaCase
    NoImplicitPrelude
    OverloadedStrings
    StrictData

  ghc-options:
    -Wall
    -Wcompat
    -Widentities
    -Wincomplete-record-updates
    -Wincomplete-uni-patterns
    -Wpartial-fields
    -Wredundant-constraints

  default-language: GHC2021

common rts
  ghc-options:
    -threaded
    -rtsopts
    -with-rtsopts=-N

library
  import: language
  hs-source-dirs: src
  build-depends:
    base >=4.11 && <5,
    bytestring,
    exceptions,
    template-haskell,
    text,
    text-builder-linear,
    text-display >=1,
    text-short,
    transformers,
    unliftio,

  extra-libraries: alpm
  build-tool-depends: c2hs:c2hs
  -- Generated with c2hs
  exposed-modules:
    Archlinux.Alpm
    Archlinux.Alpm.Package.Types

  other-modules:
    Parser
    Parser.TH
    ShortByteString.Extra
    ShortText.Extra

test-suite test
  import: language
  import: rts
  type: exitcode-stdio-1.0
  hs-source-dirs: test
  main-is: Spec.hs
  build-depends:
    QuickCheck,
    alpm,
    base,
    directory,
    effectful,
    filepath,
    hspec,
    log-base,
    log-effectful,
    path,
    path-io,
    relude,
    typed-process-effectful,

  build-tool-depends: hspec-discover:hspec-discover
  -- cabal-gild: discover test/ --include=test/**/*.hs --exclude=test/Spec.hs
  other-modules:
    Archlinux.AlpmSpec

  other-modules: PackageInfo_alpm
  autogen-modules: PackageInfo_alpm

source-repository head
  type: git
  location: https://github.com/mmhat/dhalpm
